"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Tab = "today" | "mosel" | "mood";
type User = { name: string; wineNumber: number; token: string };
type State = { participants: { id: string; name: string; wineNumber: number }[]; moodLeaderboard: { votes: number }[]; wineLeaderboard: { votes: number }[]; host: { rules: string; wineLeaderboardEnabled: boolean }; durable: boolean };

const defaultRules = `1. Melde dich mit deinem Namen und deiner Wein-Nummer an.\n2. Probiere die Weine in deinem Tempo und entdecke deinen Favoriten.\n3. Stimme für einen Wein – nur nicht für deinen eigenen.\n4. Du kannst deine Wahl bis zum Ende der Abstimmung ändern.\n5. Am Schluss küren wir gemeinsam den Gewinnerwein.`;
const moods = [["🍷", "Angeheitert"], ["🍾", "Deutlich betrunken"], ["〽", "Es geht bergab"], ["🪣", "Hackevoll"], ["🚑", "Eins vor Notarzt"]] as const;

function Arrow() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M14 6l6 6-6 6" /></svg>; }

export default function Home() {
  const [tab, setTab] = useState<Tab>("today"); const [user, setUser] = useState<User | null>(null); const [state, setState] = useState<State | null>(null);
  const [name, setName] = useState(""); const [wine, setWine] = useState(""); const [selectedWine, setSelectedWine] = useState<number | null>(null); const [savedWine, setSavedWine] = useState<number | null>(null); const [selectedPerson, setSelectedPerson] = useState<string | null>(null);
  const [hostCode, setHostCode] = useState(""); const [hostRules, setHostRules] = useState(defaultRules); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const hostRulesDirty = useRef(false);
  const numbers = useMemo(() => Array.from({ length: 30 }, (_, index) => index + 1), []);
  async function loadState() { const response = await fetch("/api/state", { cache: "no-store" }); if (response.ok) { const next = await response.json() as State; setState(next); if (!hostRulesDirty.current) setHostRules(next.host.rules); } }
  useEffect(() => { const stored = window.localStorage.getItem("weinfest-user"); if (stored) try { setUser(JSON.parse(stored)); } catch { window.localStorage.removeItem("weinfest-user"); } loadState(); const refresh = window.setInterval(loadState, 12_000); return () => window.clearInterval(refresh); }, []);
  useEffect(() => { if (!user) return; fetch("/api/me", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: user.token }) }).then(response => response.ok ? response.json() : null).then(body => { if (body?.user) { setSelectedWine(body.user.selectedWineNumber); setSavedWine(body.user.selectedWineNumber); } }).catch(() => undefined); }, [user]);
  function announce(value: string) { setMessage(value); window.setTimeout(() => setMessage(""), 5000); }
  async function enter(event: FormEvent) { event.preventDefault(); setBusy(true); try { const response = await fetch("/api/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, wineNumber: wine }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setUser(body.user); window.localStorage.setItem("weinfest-user", JSON.stringify(body.user)); announce(`Willkommen, ${body.user.name}.`); await loadState(); } catch (error) { announce(error instanceof Error ? error.message : "Anmeldung nicht möglich."); } finally { setBusy(false); } }
  async function saveWineVote() { if (!user || !selectedWine) return; setBusy(true); try { const response = await fetch("/api/vote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: user.token, selectedWineNumber: selectedWine }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSavedWine(body.vote.selectedWineNumber); announce(`Wein ${body.vote.selectedWineNumber} ist sicher gespeichert.`); await loadState(); } catch (error) { announce(error instanceof Error ? error.message : "Stimme konnte nicht gespeichert werden."); } finally { setBusy(false); } }
  async function saveMood() { if (!user || !selectedPerson) return; setBusy(true); try { const response = await fetch("/api/mood", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: user.token, participantId: selectedPerson }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSelectedPerson(null); announce("Anonym gespeichert. Die Rangliste zeigt keine Namen."); await loadState(); } catch (error) { announce(error instanceof Error ? error.message : "Stimmung konnte nicht gespeichert werden."); } finally { setBusy(false); } }
  async function saveRules() { setBusy(true); try { const response = await fetch("/api/host-rules", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code: hostCode, rules: hostRules }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); hostRulesDirty.current = false; announce("Die Regeln sind für alle Gäste gespeichert."); await loadState(); } catch (error) { announce(error instanceof Error ? error.message : "Regeln konnten nicht gespeichert werden."); } finally { setBusy(false); } }
  const ruleRows = (state?.host.rules ?? defaultRules).split("\n").filter(Boolean).map(rule => rule.replace(/^\s*\d+[.)]\s*/, ""));
  const maxMood = Math.max(...(state?.moodLeaderboard.map(item => item.votes) ?? [1]), 1); const maxWine = Math.max(...(state?.wineLeaderboard.map(item => item.votes) ?? [1]), 1);

  return <main>
    <header className="site-header"><a className="wordmark" href="/">Weinfest <em>2026</em><small>An der Mosel</small></a><nav aria-label="Bereiche">{([ ["today", "Heute"], ["mosel", "Mosel"], ["mood", "Stimmung"] ] as const).map(([key, label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</nav></header>
    <p className="toast" role="status" aria-live="polite">{message}</p>
    {tab === "today" && <div className="page">
      <section className="host-edit" aria-label="Anweisungen für Tom und Elana"><div><p className="kicker">Für Tom &amp; Elana</p><h1>Formuliert die <em>Regeln</em><br />für euren Abend.</h1><p>Öffnet die Website, schreibt eure endgültigen Regeln in dieses Feld und klickt auf „Regeln speichern“. Erst dann stehen sie fest und erscheinen direkt darunter für alle Gäste.</p></div><div className="host-fields"><label htmlFor="host-code">Host-Code</label><input id="host-code" type="password" value={hostCode} onChange={event => setHostCode(event.target.value)} placeholder="nur für Tom & Elana" /><label htmlFor="host-rules">Regeln für die Gäste</label><textarea id="host-rules" value={hostRules} onChange={event => { hostRulesDirty.current = true; setHostRules(event.target.value); }} rows={7} /><button className="button outline" disabled={busy} onClick={saveRules}>Regeln speichern <Arrow /></button></div></section>
      <section className="rules-section"><p className="kicker">So läuft der Abend</p><h2>Erst <em>anmelden</em>.<br />Dann einfach genießen.</h2><ol className="rule-flow">{ruleRows.map((rule, index) => <li key={`${index}-${rule}`}><span>{String(index + 1).padStart(2, "0")}</span><p>{rule}</p><Arrow /></li>)}</ol></section>
      {!user ? <section className="entry-section"><div><p className="kicker">Dein Zugang</p><h2>Schön, dass du <em>da</em> bist.</h2><p>Melde dich mit deinem Namen und der Nummer von deinem Namensschild an.</p></div><form onSubmit={enter}><label htmlFor="name">Dein Name</label><input id="name" value={name} onChange={event => setName(event.target.value)} minLength={2} maxLength={50} placeholder="z. B. Anna" required /><label htmlFor="wine">Deine Wein-Nummer</label><input id="wine" value={wine} onChange={event => setWine(event.target.value)} inputMode="numeric" placeholder="01" required /><button className="button" disabled={busy}>{busy ? "Wird geöffnet …" : "Weinfest betreten"} <Arrow /></button></form></section> : <section className="vote-section"><div className="vote-intro"><p className="kicker">Deine Weinwahl</p><h2>Welcher bleibt<br /><em>im Kopf?</em></h2><p>Hallo {user.name}. Deine Nummer {user.wineNumber} ist markiert und nicht wählbar.</p></div><div className="wine-numbers" role="group" aria-label="Wein auswählen">{numbers.map(number => <button key={number} className={selectedWine === number ? "selected" : ""} disabled={number === user.wineNumber} onClick={() => setSelectedWine(number)}>{number}{number === user.wineNumber && <small>dein Wein</small>}</button>)}</div>{selectedWine && <div className="save-row"><p>{selectedWine === savedWine ? <>Deine Wahl für Wein <em>{selectedWine}</em> ist nur für dich gespeichert.</> : <>Du stimmst für Wein <em>{selectedWine}</em>.</>}</p><button className="button" disabled={busy} onClick={saveWineVote}>{busy ? "Speichert …" : selectedWine === savedWine ? "Wahl erneut speichern" : "Stimme speichern"} <Arrow /></button></div>}</section>}
      <section className="hidden-wine"><div><p className="kicker">Führender Wein</p><h2>Die Spannung bleibt<br /><em>noch zu.</em></h2><p>Tom und Elana schalten diese Ansicht später bewusst frei.</p></div>{state?.host.wineLeaderboardEnabled ? <div className="anonymous-bars">{state.wineLeaderboard.slice(0, 5).map((item, index) => <div className="bar-row" key={index}><span>Platz {index + 1}</span><i><b style={{ width: `${(item.votes / maxWine) * 100}%` }} /></i></div>)}</div> : <div className="sealed">◌</div>}</section>
    </div>}
    {tab === "mosel" && <article className="mosel-page"><header><p className="kicker">Das Tal zwischen Koblenz und Trier</p><h1>Die Mosel –<br /><em>gemacht für Genuss.</em></h1><p className="lead">Sie ist nicht nur ein Fluss, sondern eine Landschaft, die sich Zeit nimmt: in jeder Schleife, auf jedem steilen Hang und in jedem Glas Riesling.</p></header><img className="mosel-image" src="/mosel-article.png" alt="Blick über einen Moselbogen mit Weinbergen" /><section className="article-copy"><div><p className="kicker">Warum hier Wein wächst</p><h2>Schiefer speichert die Wärme.</h2></div><div><p>Die steilen Hänge entlang der Mosel bestehen vielerorts aus dunklem Devonschiefer. Er nimmt tagsüber Wärme auf und gibt sie langsam wieder ab. Zusammen mit dem Fluss, der Licht zurück in die Weinberge reflektiert, entsteht ein erstaunlich mildes Kleinklima.</p><p>Genau diese Mischung macht die Mosel so besonders: Riesling bleibt frisch und fein, zugleich entwickelt er Duft nach Pfirsich, Apfel, Zitrus und manchmal eine mineralische, fast salzige Note.</p></div></section><section className="article-copy reverse"><div><p className="kicker">Der Rhythmus der Mosel</p><h2>Langsam am Wasser,<br /><em>steil am Hang.</em></h2></div><div><p>Zwischen Trier und Koblenz zählt jeder kleine Weinberg zu einem Mosaik aus Dörfern, Burgen und Terrassen. Viele Flächen können nur von Hand bewirtschaftet werden. Der Weinbau ist hier deshalb kein Nebendarsteller, sondern prägt das ganze Tal.</p><p>Für unser Weinfest ist das die passende Haltung: lieber einen Wein bewusst probieren, über ihn sprechen und eine echte Lieblingsflasche finden, statt einfach nur weiterzuziehen.</p></div></section><figure className="quote">„Die Mosel zeigt, dass Eleganz nicht laut sein muss.“</figure></article>}
    {tab === "mood" && <section className="mood-page"><header><p className="kicker">Die anonyme Hausfrage</p><h1>Wer ist gerade<br /><em>am vollsten?</em></h1><p>Wähle einmal einen Namen aus. Danach verschwinden alle Namen wieder – die Rangliste bleibt bewusst anonym.</p></header>{!user ? <p className="empty-note">Bitte melde dich zuerst im Tab „Heute“ an, dann kannst du anonym mitmachen.</p> : <><div className="mood-picker"><label htmlFor="mood-person">Teilnehmer auswählen</label><select id="mood-person" value={selectedPerson ?? ""} onChange={event => setSelectedPerson(event.target.value || null)}><option value="">Name und Wein-Nummer auswählen</option>{state?.participants.map(person => <option key={person.id} value={person.id}>{person.name} – {person.wineNumber}</option>)}</select><p>Neue Teilnehmer erscheinen automatisch. Lade die Seite ab und zu neu, damit du sicher den neuesten Stand siehst.</p><button className="button outline small-button" onClick={loadState}>Teilnehmer aktualisieren <Arrow /></button></div>{selectedPerson && <button className="button" disabled={busy} onClick={saveMood}>{busy ? "Speichert …" : "Anonym bestätigen"} <Arrow /></button>}<section className="leaderboard"><div><p className="kicker">So steht’s gerade</p><h2>Völlig <em>anonym.</em></h2></div>{state?.moodLeaderboard.length ? <div className="anonymous-bars">{state.moodLeaderboard.slice(0, 5).map((item, index) => <div className="bar-row" key={index}><span>Platz {index + 1}</span><i><b style={{ width: `${(item.votes / maxMood) * 100}%` }} /></i></div>)}</div> : <p className="empty-note">Die ersten anonymen Stimmen machen die Balken sichtbar.</p>}<div className="mood-scale">{moods.map(([icon, label], index) => <div key={label} className={index % 2 ? "lower" : ""}><span>{icon}</span><p>{label}</p></div>)}</div></section></>}</section>}
    <footer>Weinfest 2026 · Mosel <a href="/api/health">Systemstatus</a></footer>
  </main>;
}
